effect @a[scores={holding=1}] speed 2 0 true
effect @a[scores={holding=1}] strength 1 0 true
effect @a[scores={holding=2}] speed 2 1 true
effect @a[scores={holding=2}] strength 1 1 true
effect @a[scores={holding=3}] speed 2 2 true
effect @a[scores={holding=3}] strength 1 2 true
effect @a[scores={holding=3}] regeneration 2 0 true
effect @a[scores={holding=4}] speed 2 3 true
effect @a[scores={holding=4}] strength 1 3 true
effect @a[scores={holding=4}] absorption 2 0 true
effect @a[scores={holding=4}] regeneration 4 1 true